interpreter: print module loading info with -v

diff --git a/tests/interpreter_tests/interactive b/tests/interpreter_tests/interactive
--- a/tests/interpreter_tests/interactive
+++ b/tests/interpreter_tests/interactive
@@ -46,6 +46,22 @@ if [ "$CONTENTS" != 'Hello, Kos!' ]; then
 fi
 
 ##############################################################################
+# Test -v
+
+"$KOS" -v -c 'print("Hello")' > "$OUTPUT"
+
+if ! grep -q "Kos module search paths: \., " "$OUTPUT"; then
+    echo "Expected output to contain module search paths, but they are missing" >&2
+    cat "$OUTPUT"
+    exit 1
+fi
+if ! grep -q "Kos loading module lang from" "$OUTPUT"; then
+    echo "Expected output to contain information about loaded module lang, but it is missing" >&2
+    cat "$OUTPUT"
+    exit 1
+fi
+
+##############################################################################
 # Test -c in conjunction with script arguments
 
 "$KOS" --command "print(integer(args[0]) + integer(args[1]))" 20 -5 > "$OUTPUT"
